In [3]:
import pandas as pd
import requests

semcon = "http://localhost:4000"
key = "1c473003bc6e7b1d111cf3ab78f7a2fe70aa9f3dbce2dc9fa72bc28dfb1c434d"
secret = "400aff3d20d09823d3928e2587db15c824b5818449a5b67c423c721f15c54885"

def generate_token(url, client_id, client_secret):
    """Retrieve OAuth2 bearer token."""
    auth = (client_id, client_secret)
    body = {"grant_type": "client_credentials"}
    r = requests.post(url + "/oauth/token", auth=auth, json=body)
    return r.json().get('access_token')

def get_data(semcon, key, secret):
    headers = {"Authorization":"Bearer " + generate_token(semcon, key, secret), 
               "Accept": "application/json"}
    r = requests.get(semcon + '/api/data/plain', headers=headers)
    return pd.DataFrame(r.json())

df = get_data(semcon, key, secret)

# View the first ten rows
df.tail(10)

,deviceId,id,time,type,units,value
2420,DexG4Rec_SM45143452,peph81u3a4k9017p3ogof8tmtv9f38cp,2015-12-13T23:12:03,cbg,mmol/L,10.683374
2421,DexG4Rec_SM45143452,viohrdnfnuv0m5r2j8hbrfr043e2gnl1,2015-12-13T23:17:03,cbg,mmol/L,11.359428
2422,DexG4Rec_SM45143452,gku999tstiku7diduiggjbcj4o2gkgv6,2015-12-13T23:22:03,cbg,mmol/L,11.510150
2423,DexG4Rec_SM45143452,9hsh6574mnah0o2fd0mo1l0e0ltekoiu,2015-12-13T23:27:03,cbg,mmol/L,11.837021
2424,DexG4Rec_SM45143452,jnmh1s40ro476dlatdrtuar8cbuhq8qg,2015-12-13T23:32:03,cbg,mmol/L,11.538888
2425,DexG4Rec_SM45143452,5dabh6rj8gbnjbdal9kop5attoci5949,2015-12-13T23:37:03,cbg,mmol/L,11.529165
2426,DexG4Rec_SM45143452,podbb47v48mh7acspijsii19vmlvgtkj,2015-12-13T23:42:03,cbg,mmol/L,11.475984
2427,DexG4Rec_SM45143452,6sdo6ea5bmkasj4j3ef25gs1sfetn2ue,2015-12-13T23:47:03,cbg,mmol/L,11.592126
2428,DexG4Rec_SM45143452,719ht7lfsu95v65ot4909qrlvn0d3soh,2015-12-13T23:52:03,cbg,mmol/L,11.393255
2429,DexG4Rec_SM45143452,31m9q74cs8lslujphb90c6pg1u5fhatt,2015-12-13T23:57:03,cbg,mmol/L,11.349936